package org.np.stoman.persistence;

// Generated 17 Oct, 2010 12:55:11 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * PurchaseOrderMonitors generated by hbm2java
 */
public class PurchaseOrderMonitors implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1414282868505973263L;
	private int purchaseOrderMonitorId;
	private PurchaseMaterials purchaseMaterials;
	private Users users;
	private Date receivedDate;
	private int receivedQuantity;
	private Date modifiedDate;
	private BigDecimal tranportationCharge;

	public PurchaseOrderMonitors() {
	}

	public PurchaseOrderMonitors(int purchaseOrderMonitorId,
			PurchaseMaterials purchaseMaterials, Users users,
			Date receivedDate, int receivedQuantity, Date modifiedDate) {
		this.purchaseOrderMonitorId = purchaseOrderMonitorId;
		this.purchaseMaterials = purchaseMaterials;
		this.users = users;
		this.receivedDate = receivedDate;
		this.receivedQuantity = receivedQuantity;
		this.modifiedDate = modifiedDate;
	}

	public PurchaseOrderMonitors(int purchaseOrderMonitorId,
			PurchaseMaterials purchaseMaterials, Users users,
			Date receivedDate, int receivedQuantity, Date modifiedDate,
			BigDecimal tranportationCharge) {
		this.purchaseOrderMonitorId = purchaseOrderMonitorId;
		this.purchaseMaterials = purchaseMaterials;
		this.users = users;
		this.receivedDate = receivedDate;
		this.receivedQuantity = receivedQuantity;
		this.modifiedDate = modifiedDate;
		this.tranportationCharge = tranportationCharge;
	}

	public int getPurchaseOrderMonitorId() {
		return this.purchaseOrderMonitorId;
	}

	public void setPurchaseOrderMonitorId(int purchaseOrderMonitorId) {
		this.purchaseOrderMonitorId = purchaseOrderMonitorId;
	}

	public PurchaseMaterials getPurchaseMaterials() {
		return this.purchaseMaterials;
	}

	public void setPurchaseMaterials(PurchaseMaterials purchaseMaterials) {
		this.purchaseMaterials = purchaseMaterials;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getReceivedDate() {
		return this.receivedDate;
	}

	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}

	public int getReceivedQuantity() {
		return this.receivedQuantity;
	}

	public void setReceivedQuantity(int receivedQuantity) {
		this.receivedQuantity = receivedQuantity;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public BigDecimal getTranportationCharge() {
		return this.tranportationCharge;
	}

	public void setTranportationCharge(BigDecimal tranportationCharge) {
		this.tranportationCharge = tranportationCharge;
	}

}
