package org.np.stoman.persistence;

// Generated 17 Oct, 2010 12:55:11 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

/**
 * PurchaseMaterials generated by hbm2java
 */
public class PurchaseMaterials implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -165925518677180610L;
	private int purchaseMaterialId;
	private PurchaseOrders purchaseOrders;
	private VendorMaterials vendorMaterials;
	private Users users;
	private Date date;
	private int orderedQuantity;
	private int receivedQuantity;
	private int createdBy;
	private Integer modifiedDate;
	private Date dueDate;
	private Date delieveredDate;
	private Date cancelledDate;
	private BigDecimal transportatonCharge;

	public PurchaseMaterials() {
	}

	public PurchaseMaterials(int purchaseMaterialId,
			PurchaseOrders purchaseOrders, VendorMaterials vendorMaterials,
			Date date, int orderedQuantity, int receivedQuantity, int createdBy) {
		this.purchaseMaterialId = purchaseMaterialId;
		this.purchaseOrders = purchaseOrders;
		this.vendorMaterials = vendorMaterials;
		this.date = date;
		this.orderedQuantity = orderedQuantity;
		this.receivedQuantity = receivedQuantity;
		this.createdBy = createdBy;
	}

	public PurchaseMaterials(int purchaseMaterialId,
			PurchaseOrders purchaseOrders, VendorMaterials vendorMaterials,
			Users users, Date date, int orderedQuantity, int receivedQuantity,
			int createdBy, Integer modifiedDate, Date dueDate,
			Date delieveredDate, Date cancelledDate,
			BigDecimal transportatonCharge,
			Set<PurchaseOrderMonitors> purchaseOrderMonitorses) {
		this.purchaseMaterialId = purchaseMaterialId;
		this.purchaseOrders = purchaseOrders;
		this.vendorMaterials = vendorMaterials;
		this.users = users;
		this.date = date;
		this.orderedQuantity = orderedQuantity;
		this.receivedQuantity = receivedQuantity;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.dueDate = dueDate;
		this.delieveredDate = delieveredDate;
		this.cancelledDate = cancelledDate;
		this.transportatonCharge = transportatonCharge;
	}

	public int getPurchaseMaterialId() {
		return this.purchaseMaterialId;
	}

	public void setPurchaseMaterialId(int purchaseMaterialId) {
		this.purchaseMaterialId = purchaseMaterialId;
	}

	public PurchaseOrders getPurchaseOrders() {
		return this.purchaseOrders;
	}

	public void setPurchaseOrders(PurchaseOrders purchaseOrders) {
		this.purchaseOrders = purchaseOrders;
	}

	public VendorMaterials getVendorMaterials() {
		return this.vendorMaterials;
	}

	public void setVendorMaterials(VendorMaterials vendorMaterials) {
		this.vendorMaterials = vendorMaterials;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getOrderedQuantity() {
		return this.orderedQuantity;
	}

	public void setOrderedQuantity(int orderedQuantity) {
		this.orderedQuantity = orderedQuantity;
	}

	public int getReceivedQuantity() {
		return this.receivedQuantity;
	}

	public void setReceivedQuantity(int receivedQuantity) {
		this.receivedQuantity = receivedQuantity;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public Integer getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Integer modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	public Date getDelieveredDate() {
		return this.delieveredDate;
	}

	public void setDelieveredDate(Date delieveredDate) {
		this.delieveredDate = delieveredDate;
	}

	public Date getCancelledDate() {
		return this.cancelledDate;
	}

	public void setCancelledDate(Date cancelledDate) {
		this.cancelledDate = cancelledDate;
	}

	public BigDecimal getTransportatonCharge() {
		return this.transportatonCharge;
	}

	public void setTransportatonCharge(BigDecimal transportatonCharge) {
		this.transportatonCharge = transportatonCharge;
	}

}
