package org.np.stoman.persistence;

// Generated 17 Oct, 2010 12:55:11 PM by Hibernate Tools 3.2.2.GA

/**
 * RankArchives generated by hbm2java
 */
public class RankArchives implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4013913888166123913L;
	private int rankArchiveId;
	private Vendors vendors;
	private Users users;
	private int rank;
	private String expiredDate;

	public RankArchives() {
	}

	public RankArchives(int rankArchiveId, Vendors vendors, Users users,
			int rank, String expiredDate) {
		this.rankArchiveId = rankArchiveId;
		this.vendors = vendors;
		this.users = users;
		this.rank = rank;
		this.expiredDate = expiredDate;
	}

	public int getRankArchiveId() {
		return this.rankArchiveId;
	}

	public void setRankArchiveId(int rankArchiveId) {
		this.rankArchiveId = rankArchiveId;
	}

	public Vendors getVendors() {
		return this.vendors;
	}

	public void setVendors(Vendors vendors) {
		this.vendors = vendors;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public String getExpiredDate() {
		return this.expiredDate;
	}

	public void setExpiredDate(String expiredDate) {
		this.expiredDate = expiredDate;
	}

}
