package org.np.stoman.persistence;

// Generated 17 Oct, 2010 12:55:11 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Ranks generated by hbm2java
 */
public class Ranks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6751324748718938223L;
	private int rankId;
	private Vendors vendors;
	private Users users;
	private int rank;
	private Integer trustLevel;
	private Date modifiedDate;

	public Ranks() {
	}

	public Ranks(int rankId, Vendors vendors, Users users, int rank,
			Date modifiedDate) {
		this.rankId = rankId;
		this.vendors = vendors;
		this.users = users;
		this.rank = rank;
		this.modifiedDate = modifiedDate;
	}

	public Ranks(int rankId, Vendors vendors, Users users, int rank,
			Integer trustLevel, Date modifiedDate) {
		this.rankId = rankId;
		this.vendors = vendors;
		this.users = users;
		this.rank = rank;
		this.trustLevel = trustLevel;
		this.modifiedDate = modifiedDate;
	}

	public int getRankId() {
		return this.rankId;
	}

	public void setRankId(int rankId) {
		this.rankId = rankId;
	}

	public Vendors getVendors() {
		return this.vendors;
	}

	public void setVendors(Vendors vendors) {
		this.vendors = vendors;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public Integer getTrustLevel() {
		return this.trustLevel;
	}

	public void setTrustLevel(Integer trustLevel) {
		this.trustLevel = trustLevel;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
