package org.np.stoman.persistence;

// Generated 17 Oct, 2010 12:55:11 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2466139531774138792L;
	private int userId;
	private Addresses addresses;
	private String name;
	private String role;
	private Date createdOn;

	public Users() {
	}

	public Users(int userId, String name, String role, Date createdOn) {
		this.userId = userId;
		this.name = name;
		this.role = role;
		this.createdOn = createdOn;
	}

	public Users(int userId, Addresses addresses, String name, String role,
			Date createdOn, Set<PurchaseMaterials> purchaseMaterialses,
			Set<VendorMaterials> vendorMaterialses,
			Set<PurchaseOrderMonitors> purchaseOrderMonitorses,
			Set<RankArchives> rankArchiveses,
			Set<VendorMaterialArchives> vendorMaterialArchiveses,
			Set<Ranks> rankses) {
		this.userId = userId;
		this.addresses = addresses;
		this.name = name;
		this.role = role;
		this.createdOn = createdOn;

	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Addresses getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Addresses addresses) {
		this.addresses = addresses;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

}
