package org.np.stoman.persistence;

// Generated 17 Oct, 2010 12:55:11 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.Set;

/**
 * VendorMaterials generated by hbm2java
 */
public class VendorMaterials implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5162973170913935714L;
	private int vendorMaterialId;
	private Vendors vendors;
	private Materials materials;
	private Users users;
	private Date priceStartDate;
	private Date modifiedDate;
	private Integer maxQtyPerOrder;
	private String data;

	public VendorMaterials() {
	}

	public VendorMaterials(int vendorMaterialId, Vendors vendors,
			Materials materials, Users users, Date priceStartDate,
			Date modifiedDate) {
		this.vendorMaterialId = vendorMaterialId;
		this.vendors = vendors;
		this.materials = materials;
		this.users = users;
		this.priceStartDate = priceStartDate;
		this.modifiedDate = modifiedDate;
	}

	public VendorMaterials(int vendorMaterialId, Vendors vendors,
			Materials materials, Users users, Date priceStartDate,
			Date modifiedDate, Integer maxQtyPerOrder,
			Set<PurchaseMaterials> purchaseMaterialses) {
		this.vendorMaterialId = vendorMaterialId;
		this.vendors = vendors;
		this.materials = materials;
		this.users = users;
		this.priceStartDate = priceStartDate;
		this.modifiedDate = modifiedDate;
		this.maxQtyPerOrder = maxQtyPerOrder;
	}

	public int getVendorMaterialId() {
		return this.vendorMaterialId;
	}

	public void setVendorMaterialId(int vendorMaterialId) {
		this.vendorMaterialId = vendorMaterialId;
	}

	public Vendors getVendors() {
		return this.vendors;
	}

	public void setVendors(Vendors vendors) {
		this.vendors = vendors;
	}

	public Materials getMaterials() {
		return this.materials;
	}

	public void setMaterials(Materials materials) {
		this.materials = materials;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getPriceStartDate() {
		return this.priceStartDate;
	}

	public void setPriceStartDate(Date priceStartDate) {
		this.priceStartDate = priceStartDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public Integer getMaxQtyPerOrder() {
		return this.maxQtyPerOrder;
	}

	public void setMaxQtyPerOrder(Integer maxQtyPerOrder) {
		this.maxQtyPerOrder = maxQtyPerOrder;
	}

	public String getData() {
		return data;
	}

	public void setData(String data) {
		this.data = data;
	}
}
