package org.np.stoman.persistence;

// Generated 17 Oct, 2010 12:55:11 PM by Hibernate Tools 3.2.2.GA

import java.util.Set;

/**
 * Vendors generated by hbm2java
 */
public class Vendors implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5298791763553134214L;
	private int vendorId;
	private Addresses addresses;
	private String name;

	public Vendors() {
	}

	public Vendors(int vendorId, String name) {
		this.vendorId = vendorId;
		this.name = name;
	}

	public Vendors(int vendorId, Addresses addresses, String name,
			Set<RankArchives> rankArchiveses,
			Set<VendorMaterialArchives> vendorMaterialArchiveses,
			Set<VendorMaterials> vendorMaterialses, Set<Ranks> rankses) {
		this.vendorId = vendorId;
		this.addresses = addresses;
		this.name = name;
		
	}

	public int getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(int vendorId) {
		this.vendorId = vendorId;
	}

	public Addresses getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Addresses addresses) {
		this.addresses = addresses;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
}
