package org.np.stoman.persistence;

// Generated 17 Oct, 2010 12:55:11 PM by Hibernate Tools 3.2.2.GA


/**
 * Vendors generated by hbm2java
 */
public class Vendors implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5298791763553134214L;
	private Integer vendorId;
	private Addresses addresses;
	private String name;

	public Vendors() {
	}

	public Vendors(Integer vendorId, String name) {
		this.vendorId = vendorId;
		this.name = name;
	}

	public Vendors(Integer vendorId, Addresses addresses, String name) {
		this.vendorId = vendorId;
		this.addresses = addresses;
		this.name = name;

	}

	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	public Addresses getAddresses() {
		if (addresses == null)
			addresses = new Addresses();
		return this.addresses;
	}

	public void setAddresses(Addresses addresses) {
		this.addresses = addresses;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
